backend:
  name: github
  repo: aclrians/spiderwebnest
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: oauth2/authorize
  app_id: Ov23liFm0mWWaBDex9Ry


media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
